---
- name: INSTALLING A REQUIRED PACKAGES
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - autofs
    - nfs-utils
  notify: restart autofs

- name: STOP AUTOFS SERVICE IS ALREADY INSTALLED AND RUNNING
  service:
    name: autofs
    state: stopped
  notify: restart autofs
    
- name: CREATING A BASE MOUNT POINT
  file:
    path: "{{ item.mount_dir }}"
    mode: "0777"
    state: directory
  loop: "{{ mounts }}"

- name: CREATING A MOUNT POINT IN MOUNT DIRECTORY
  file:
    path: "{{ item.mount_dir }}/{{ item.mount_point }}"
    state: directory
    mode: "0644"
  loop: "{{ mounts }}"

- name: PREPARE MASTER MAP FILE
  template:
    src: auto.master.j2
    dest: /etc/auto.master
    mode: "0644"
  notify: restart autofs

- name: PREPARE MAP FILE FOR EACH MOUNT
  template:
    src: auto_mount.j2
    dest: /etc/auto_mount.misc
    mode: "0644"
  notify: restart autofs

- name: CONFIGURING A SELINUX
  selinux:
    policy: targeted
    state: permissive

- name: STARTING THE SERVICE FIREWALLD
  service: 
    name: firewalld
    state: restarted
    enabled: true
  notify: config firewall rules

